#!/usr/bin/perl -w

# This program will illustrate the process of reading in a VOTABLE
# document as a Astro::VO::VOTable::Document object, and then
# converting that object to a hierarchy of Perl data structures.

#------------------------------------------------------------------------------

# External modules

use Data::Dumper;

use blib '../blib';
use Astro::VO::VOTable;

#------------------------------------------------------------------------------

# Subroutine prototypes
sub _convert_document($);
sub _convert_votable($);
sub _convert_resource($);
sub _convert_description($);
sub _convert_definitions($);
sub _convert_info($);
sub _convert_param($);
sub _convert_table($);
sub _convert_field($);
sub _convert_group($);
sub _convert_min($);
sub _convert_max($);
sub _convert_option($);
sub _convert_link($);
sub _convert_data($);
sub _convert_tabledata($);
sub _convert_td($);
sub _convert_tr($);
sub _convert_fits($);
sub _convert_binary($);
sub _convert_stream($);
sub _convert_coosys($);

#------------------------------------------------------------------------------

# Save arguments.
my($filename) = @ARGV;

# Variable definitions

# Astro::VO::VOTable::Document (DOM) object for the document to
# convert.
my($vo_document);

# Perl data structure to hold the document contents.
my($document);

#------------------------------------------------------------------------------

# Read the file.
print "Reading $filename...\n";
$vo_document = Astro::VO::VOTable::Document->new_from_file($filename) or die;
print "done.\n";

# Convert the Document object to a Perl structure.
print "Converting...\n";
$document = _convert_document($vo_document);
print "done.\n";

# Print the contents.
#print "File $filename contained:\n", Dumper($document);

#------------------------------------------------------------------------------

sub _convert_document($)
{
    my($vo_document) = @_;
    my($document);
    my($vo_votable);
    my($votable);

    $document = {};
    $vo_votable = $vo_document->get_VOTABLE or die;
    $votable = _convert_votable($vo_votable) or die;
    push(@{$document->{elements}}, $votable);

    return($document);
}

#------------------------------------------------------------------------------

sub _convert_votable($)
{
    my($vo_votable) = @_;
    my($votable);
    my($id, $version);
    my($node, $tag);

    $votable = {};

    # Attributes
    $id = $vo_votable->get_ID;
    $version = $vo_votable->get_version;
    $votable->{attributes}{ID} = $id if defined($id);
    $votable->{attributes}{version} = $version if defined($version);

    # Child elements
    foreach $node ($vo_votable->childNodes) {
	$tag = $node->nodeName;
	if ($tag eq 'DESCRIPTION') {
	    push(@{$votable->{elements}}, _convert_description($node));
	} elsif ($tag eq 'DEFINITIONS') {
	    push(@{$votable->{elements}}, _convert_definitions($node));
	} elsif ($tag eq 'INFO') {
	    push(@{$votable->{elements}}, _convert_info($node));
	} elsif ($tag eq 'RESOURCE') {
	    push(@{$votable->{elements}}, _convert_resource($node));
	} elsif ($tag eq 'comment') {
	} elsif ($tag eq 'text') {
	} else {
	    die("Invalid tag for VOTABLE child: $tag!");
	}
    }

    # Text content (none)

    return($votable);
}

#------------------------------------------------------------------------------

sub _convert_resource($)
{
    my($dom_resource) = @_;
    my($vo_resource);
    my($resource);
    my($name, $id, $type);
    my($node, $tag);

    $vo_resource = Astro::VO::VOTable::RESOURCE->new($dom_resource);
    $resource = {};
    $resource->{tag} = 'RESOURCE';

    # Attributes
    $name = $vo_resource->get_name;
    $id = $vo_resource->get_ID;
    $type = $vo_resource->get_type;
    $resource->{attributes}{name} = $name if defined($name);
    $resource->{attributes}{ID} = $id if defined($id);
    $resource->{attributes}{type} = $type if defined($type);

    # Child elements
    foreach $node ($vo_resource->childNodes) {
	$tag = $node->nodeName;
	if ($tag eq 'DESCRIPTION') {
	    push(@{$resource->{elements}}, _convert_description($node));
	} elsif ($tag eq 'INFO') {
	    push(@{$resource->{elements}}, _convert_info($node));
	} elsif ($tag eq 'COOSYS') {
	    push(@{$resource->{elements}}, _convert_coosys($node));
	} elsif ($tag eq 'PARAM') {
	    push(@{$resource->{elements}}, _convert_param($node));
	} elsif ($tag eq 'LINK') {
	    push(@{$resource->{elements}}, _convert_link($node));
	} elsif ($tag eq 'TABLE') {
	    push(@{$resource->{elements}}, _convert_table($node));
	} elsif ($tag eq 'RESOURCE') {
	    push(@{$resource->{elements}}, _convert_resource($node));
	} elsif ($tag eq 'comment') {
	} elsif ($tag eq 'text') {
	} else {
	    die("Invalid tag for RESOURCE child: $tag!");
	}
    }

    # Text content (none)

    return($resource);
}

#------------------------------------------------------------------------------

sub _convert_description($)
{
    my($dom_description) = @_;
    my($vo_description);
    my($description);
    my($text);

    $vo_description = Astro::VO::VOTable::DESCRIPTION->new($dom_description)
	or die;
    $description = {};
    $description->{tag} = 'DESCRIPTION';

    # Attributes (none)

    # Child elements (none)

    # Text content (ignore whitespace)
    $text = $vo_description->get;
    $description->{text} = $text if $text =~ /\S/;

    return($description);
}

#------------------------------------------------------------------------------

sub _convert_definitions($)
{
    my($dom_definitions) = @_;
    my($vo_definitions);
    my($definitions);
    my($node, $tag);

    $vo_definitions = Astro::VO::VOTable::DEFINITIONS->new($dom_definitions)
	or die;
    $definitions = {};
    $definitions->{tag} = 'DEFINITIONS';

    # Attributes (none)

    # Child elements
    foreach $node ($vo_definitions->childNodes) {
	$tag = $node->nodeName;
	if ($tag eq 'COOSYS') {
	    push(@{$definitions->{elements}}, _convert_coosys($node));
	} elsif ($tag eq 'PARAM') {
	    push(@{$definitions->{elements}}, _convert_param($node));
	} elsif ($tag eq 'comment') {
	} elsif ($tag eq 'text') {
	} else {
	    die("Invalid tag for DEFINITIONS child: $tag!");
	}
    }

    # Text content (none)

    return($definitions);
}

#------------------------------------------------------------------------------

sub _convert_info($)
{
    my($dom_info) = @_;
    my($vo_info);
    my($info);
    my($id, $name, $value);
    my($text);

    $vo_info = Astro::VO::VOTable::INFO->new($dom_info);
    $info = {};
    $info->{tag} = 'INFO';

    # Attributes
    $id = $vo_info->get_ID;
    $name = $vo_info->get_name;
    $value = $vo_info->get_value;
    $info->{attributes}{ID} = $id if defined($id);
    $info->{attributes}{name} = $name if defined($name);
    $info->{attributes}{value} = $value if defined($value);

    # Child elements (none)

    # Text content (ignore whitespace)
    $text = $vo_info->get;
    $info->{text} = $text if $text =~ /\S/;

    return($info);
}

#------------------------------------------------------------------------------

sub _convert_param($)
{
    my($dom_param) = @_;
    my($vo_param);
    my($param);
    my($id, $unit, $datatype, $precision, $width, $ref, $name, $ucd, $utype,
       $value, $arraysize);
    my($node, $tag);

    $vo_param = Astro::VO::VOTable::PARAM->new($dom_param);
    $param = {};
    $param->{tag} = 'PARAM';

    # Attributes
    $id = $vo_param->get_ID;
    $unit = $vo_param->get_unit;
    $datatype = $vo_param->get_datatype;
    $precision = $vo_param->get_precision;
    $width = $vo_param->get_width;
    $ref = $vo_param->get_ref;
    $name = $vo_param->get_name;
    $ucd = $vo_param->get_ucd;
    $utype = $vo_param->get_utype;
    $value = $vo_param->get_value;
    $arraysize = $vo_param->get_arraysize;
    $param->{attributes}{ID} = $id if defined($id);
    $param->{attributes}{unit} = $unit if defined($unit);
    $param->{attributes}{datatype} = $datatype if defined($datatype);
    $param->{attributes}{precision} = $precision if defined($precision);
    $param->{attributes}{width} = $width if defined($width);
    $param->{attributes}{ref} = $ref if defined($ref);
    $param->{attributes}{name} = $name if defined($name);
    $param->{attributes}{ucd} = $ucd if defined($ucd);
    $param->{attributes}{utype} = $utype if defined($utype);
    $param->{attributes}{value} = $value if defined($value);
    $param->{attributes}{arraysize} = $arraysize if defined($arraysize);

    # Child elements
    foreach $node ($vo_param->childNodes) {
	$tag = $node->nodeName;
	if ($tag eq 'DESCRIPTION') {
	    push(@{$param->{elements}}, _convert_description($node));
	} elsif ($tag eq 'VALUES') {
	    push(@{$param->{elements}}, _convert_values($node));
	} elsif ($tag eq 'LINK') {
	    push(@{$param->{elements}}, _convert_link($node));
	} elsif ($tag eq 'comment') {
	} elsif ($tag eq 'text') {
	} else {
	    die("Invalid tag for PARAM child: $tag!");
	}
    }

    # Text content (none)

    return($param);
}

#------------------------------------------------------------------------------

sub _convert_table($)
{
    my($dom_table) = @_;
    my($vo_table);
    my($table);
    my($id, $name, $ref);
    my($node, $tag);

    $vo_table = Astro::VO::VOTable::TABLE->new($dom_table);
    $table = {};
    $table->{tag} = 'TABLE';

    # Attributes
    $id = $vo_table->get_ID;
    $name = $vo_table->get_name;
    $ref = $vo_table->get_ref;
    $table->{attributes}{ID} = $id if defined($id);
    $table->{attributes}{name} = $name if defined($name);
    $table->{attributes}{ref} = $ref if defined($ref);

    # Child elements
    foreach $node ($vo_table->childNodes) {
	$tag = $node->nodeName;
	if ($tag eq 'DESCRIPTION') {
	    push(@{$table->{elements}}, _convert_description($node));
	} elsif ($tag eq 'FIELD') {
	    push(@{$table->{elements}}, _convert_field($node));
	} elsif ($tag eq 'PARAM') {
	    push(@{$table->{elements}}, _convert_param($node));
	} elsif ($tag eq 'GROUP') {
	    push(@{$table->{elements}}, _convert_group($node));
	} elsif ($tag eq 'LINK') {
	    push(@{$table->{elements}}, _convert_link($node));
	} elsif ($tag eq 'DATA') {
	    push(@{$table->{elements}}, _convert_data($node));
	} elsif ($tag eq 'comment') {
	} elsif ($tag eq 'text') {
	} else {
	    die("Invalid tag for TABLE child: $tag!");
	}
    }

    # Text content (none)

    return($table);
}

#------------------------------------------------------------------------------

sub _convert_field($)
{
    my($dom_field) = @_;
    my($vo_field);
    my($field);
    my($id, $unit, $datatype, $precision, $width, $ref, $name, $ucd, $utype,
       $arraysize, $type);
    my($node, $tag);

    $vo_field = Astro::VO::VOTable::FIELD->new($dom_field);
    $field = {};
    $field->{tag} = 'FIELD';

    # Attributes
    $id = $vo_field->get_ID;
    $unit = $vo_field->get_unit;
    $datatype = $vo_field->get_datatype;
    $precision = $vo_field->get_precision;
    $width = $vo_field->get_width;
    $ref = $vo_field->get_ref;
    $name = $vo_field->get_name;
    $ucd = $vo_field->get_ucd;
    $utype = $vo_field->get_utype;
    $arraysize = $vo_field->get_arraysize;
    $type = $vo_field->get_type;
    $field->{attributes}{ID} = $id if defined($id);
    $field->{attributes}{unit} = $unit if defined($unit);
    $field->{attributes}{datatype} = $datatype if defined($datatype);
    $field->{attributes}{precision} = $precision if defined($precision);
    $field->{attributes}{width} = $width if defined($width);
    $field->{attributes}{ref} = $ref if defined($ref);
    $field->{attributes}{name} = $name if defined($name);
    $field->{attributes}{ucd} = $ucd if defined($ucd);
    $field->{attributes}{utype} = $utype if defined($utype);
    $field->{attributes}{arraysize} = $arraysize if defined($arraysize);
    $field->{attributes}{type} = $type if defined($type);

    # Child elements
    foreach $node ($vo_field->childNodes) {
	$tag = $node->nodeName;
	if ($tag eq 'DESCRIPTION') {
	    push(@{$field->{elements}}, _convert_description($node));
	} elsif ($tag eq 'VALUES') {
	    push(@{$field->{elements}}, _convert_values($node));
	} elsif ($tag eq 'LINK') {
	    push(@{$field->{elements}}, _convert_link($node));
	} elsif ($tag eq 'comment') {
	} elsif ($tag eq 'text') {
	} else {
	    die("Invalid tag for FIELD child: $tag!");
	}
    }

    # Text content (none)

    return($field);
}

#------------------------------------------------------------------------------

sub _convert_group($)
{
    my($dom_group) = @_;
    my($vo_group);
    my($group);
    my($id, $name, $ref, $ucd, $utype);
    my($node, $tag);

    $vo_group = Astro::VO::VOTable::GROUP->new($dom_group);
    $group = {};
    $group->{tag} = 'GROUP';

    # Attributes
    $id = $vo_group->get_ID;
    $name = $vo_group->get_name;
    $ref = $vo_group->get_ref;
    $ucd = $vo_group->get_ucd;
    $utype = $vo_group->get_utype;
    $group->{attributes}{ID} = $id if defined($id);
    $group->{attributes}{name} = $name if defined($name);
    $group->{attributes}{ref} = $ref if defined($ref);
    $group->{attributes}{ucd} = $ucd if defined($ucd);
    $group->{attributes}{utype} = $utype if defined($utype);

    # Child elements
    foreach $node ($vo_group->childNodes) {
	$tag = $node->nodeName;
	if ($tag eq 'FIELD') {
	    push(@{$group->{elements}}, _convert_field($node));
	} elsif ($tag eq 'PARAM') {
	    push(@{$group->{elements}}, _convert_param($node));
	} elsif ($tag eq 'GROUP') {
	    push(@{$group->{elements}}, _convert_group($node));
	} elsif ($tag eq 'comment') {
	} elsif ($tag eq 'text') {
	} else {
	    die("Invalid tag for GROUP child: $tag!");
	}
    }

    # Text content (none)

    return($group);
}

#------------------------------------------------------------------------------

sub _convert_values($)
{
    my($dom_values) = @_;
    my($vo_values);
    my($values);
    my($id, $type, $null, $ref);
    my($node, $tag);

    $vo_values = Astro::VO::VOTable::VALUES->new($dom_values);
    $values = {};
    $values->{tag} = 'VALUES';

    # Attributes
    $id = $vo_values->get_ID;
    $type = $vo_values->get_type;
    $null = $vo_values->get_null;
    $ref = $vo_values->get_ref;
    $values->{attributes}{ID} = $id if defined($id);
    $values->{attributes}{type} = $type if defined($type);
    $values->{attributes}{null} = $null if defined($null);
    $values->{attributes}{ref} = $ref if defined($ref);

    # Child elements
    foreach $node ($vo_values->childNodes) {
	$tag = $node->nodeName;
	if ($tag eq 'MIN') {
	    push(@{$values->{elements}}, _convert_min($node));
	} elsif ($tag eq 'MAX') {
	    push(@{$values->{elements}}, _convert_max($node));
	} elsif ($tag eq 'OPTION') {
	    push(@{$values->{elements}}, _convert_option($node));
	} elsif ($tag eq 'comment') {
	} elsif ($tag eq 'text') {
	} else {
	    die("Invalid tag for VALUES child: $tag!");
	}
    }

    # Text content (none)

    return($values);
}

#------------------------------------------------------------------------------

sub _convert_min($)
{
    my($dom_min) = @_;
    my($vo_min);
    my($min);
    my($value, $inclusive);

    $vo_min = Astro::VO::VOTable::MIN->new($dom_min);
    $min = {};
    $min->{tag} = 'MIN';

    # Attributes
    $value = $vo_min->get_value;
    $inclusive = $vo_min->get_inclusive;
    $min->{attributes}{value} = $value if defined($value);
    $min->{attributes}{inclusive} = $inclusive if defined($inclusive);

    # Child elements (none)

    # Text content (none)

    return($min);
}

#------------------------------------------------------------------------------

sub _convert_max($)
{
    my($dom_max) = @_;
    my($vo_max);
    my($max);
    my($value, $inclusive);

    $vo_max = Astro::VO::VOTable::MAX->new($dom_max);
    $max = {};
    $max->{tag} = 'MAX';

    # Attributes
    $value = $vo_max->get_value;
    $inclusive = $vo_max->get_inclusive;
    $max->{attributes}{value} = $value if defined($value);
    $max->{attributes}{inclusive} = $inclusive if defined($inclusive);

    # Child elements (none)

    # Text content (none)

    return($max);
}

#------------------------------------------------------------------------------

sub _convert_option($)
{
    my($dom_option) = @_;
    my($vo_option);
    my($option);
    my($name, $value);
    my($node, $tag);

    $vo_option = Astro::VO::VOTable::OPTION->new($dom_option);
    $option = {};
    $option->{tag} = 'OPTION';

    # Attributes
    $name = $vo_option->get_name;
    $value = $vo_option->get_value;
    $option->{attributes}{name} = $name if defined($name);
    $option->{attributes}{value} = $value if defined($value);

    # Child elements
    foreach $node ($vo_option->childNodes) {
	$tag = $node->nodeName;
	if ($tag eq 'OPTION') {
	    push(@{$option->{elements}}, _convert_option($node));
	} elsif ($tag eq 'comment') {
	} elsif ($tag eq 'text') {
	} else {
	    die("Invalid tag for OPTION child: $tag!");
	}
    }

    # Text content (none)

    return($option);
}

#------------------------------------------------------------------------------

sub _convert_link($)
{
    my($dom_link) = @_;
    my($vo_link);
    my($link);
    my($id, $content_role, $content_type, $title, $value, $href, $gref,
       $action);
    my($text);

    $vo_link = Astro::VO::VOTable::LINK->new($dom_link);
    $link = {};
    $link->{tag} = 'LINK';

    # Attributes
    $id = $vo_link->get_ID;
    $content_role = $vo_link->get_content_role;
    $content_type = $vo_link->get_content_type;
    $title = $vo_link->get_title;
    $value = $vo_link->get_value;
    $href = $vo_link->get_href;
    $gref = $vo_link->get_gref;
    $action = $vo_link->get_action;
    $link->{attributes}{ID} = $id if defined($id);
    $link->{attributes}{'content-role'} = $id if defined($content_role);
    $link->{attributes}{'content-type'} = $content_type
	if defined($content_type);
    $link->{attributes}{title} = $title if defined($title);
    $link->{attributes}{value} = $value if defined($value);
    $link->{attributes}{href} = $href if defined($href);
    $link->{attributes}{gref} = $gref if defined($gref);
    $link->{attributes}{action} = $action if defined($action);

    # Child elements (none)

    # Text content (ignore whitespace)
    $text = $vo_link->get;
    $link->{text} = $text if $text =~ /\S/;

    return($link);
}

#------------------------------------------------------------------------------

sub _convert_data($)
{
    my($dom_data) = @_;
    my($vo_data);
    my($data);
    my($node, $tag);

    $vo_data = Astro::VO::VOTable::DATA->new($dom_data);
    $data = {};
    $data->{tag} = 'DATA';

    # Attributes (none)

    # Child elements
    foreach $node ($vo_data->childNodes) {
	$tag = $node->nodeName;
	if ($tag eq 'TABLEDATA') {
	    push(@{$data->{elements}}, _convert_tabledata($node));
	} elsif ($tag eq 'BINARY') {
	    push(@{$data->{elements}}, _convert_binary($node));
	} elsif ($tag eq 'FITS') {
	    push(@{$data->{elements}}, _convert_fits($node));
	} elsif ($tag eq 'comment') {
	} elsif ($tag eq 'text') {
	} else {
	    die("Invalid tag for DATA child: $tag!");
	}
    }

    # Text content (none)

    return($data);
}

#------------------------------------------------------------------------------

sub _convert_tabledata($)
{
    my($dom_tabledata) = @_;
    my($vo_tabledata);
    my($tabledata);
    my($node, $tag);

    $vo_tabledata = Astro::VO::VOTable::TABLEDATA->new($dom_tabledata);
    $tabledata = {};
    $tabledata->{tag} = 'TABLEDATA';

    # Attributes (none)

    # Child elements
    foreach $node ($vo_tabledata->childNodes) {
	$tag = $node->nodeName;
	if ($tag eq 'TR') {
	    push(@{$tabledata->{elements}}, _convert_tr($node));
	} elsif ($tag eq 'comment') {
	} elsif ($tag eq 'text') {
	} else {
	    die("Invalid tag for TABLEDATA child: $tag!");
	}
    }

    # Text content (none)

    return($tabledata);
}

#------------------------------------------------------------------------------

sub _convert_td($)
{
    my($dom_td) = @_;
    my($vo_td);
    my($td);
    my($text);

    $vo_td = Astro::VO::VOTable::TD->new($dom_td);
    $td = {};
    $td->{tag} = 'TD';

    # Attributes (none)

    # Child elements (none)

    # Text content (all)
    $text = $vo_td->get;
    $td->{text} = $text;

    return($td);
}

#------------------------------------------------------------------------------

sub _convert_tr($)
{
    my($dom_tr) = @_;
    my($vo_tr);
    my($tr);
    my($node, $tag);

    $vo_tr = Astro::VO::VOTable::TR->new($dom_tr);
    $tr = {};
    $tr->{tag} = 'TR';

    # Attributes (none)

    # Child elements
    foreach $node ($vo_tr->childNodes) {
	$tag = $node->nodeName;
	if ($tag eq 'TD') {
	    push(@{$tr->{elements}}, _convert_td($node));
	} elsif ($tag eq 'comment') {
	} elsif ($tag eq 'text') {
	} else {
	    die("Invalid tag for TR child: $tag!");
	}
    }

    # Text content (none)

    return($tr);
}

#------------------------------------------------------------------------------

sub _convert_fits($)
{
    my($dom_fits) = @_;
    my($vo_fits);
    my($fits);
    my($extnum);
    my($node, $tag);

    $vo_fits = Astro::VO::VOTable::FITS->new($dom_fits);
    $fits = {};
    $fits->{tag} = 'FITS';

    # Attributes
    $extnum = $vo_fits->get_extnum;
    $fits->{attributes}{extnum} = $extnum if defined($extnum);

    # Child elements
    foreach $node ($vo_fits->childNodes) {
	$tag = $node->nodeName;
	if ($tag eq 'STREAM') {
	    push(@{$fits->{elements}}, _convert_stream($node));
	} elsif ($tag eq 'comment') {
	} elsif ($tag eq 'text') {
	} else {
	    die("Invalid tag for FITS child: $tag!");
	}
    }

    # Text content (none)

    return($fits);
}

#------------------------------------------------------------------------------

sub _convert_binary($)
{
    my($dom_binary) = @_;
    my($vo_binary);
    my($binary);
    my($node, $tag);

    $vo_binary = Astro::VO::VOTable::BINARY->new($dom_binary);
    $binary = {};
    $binary->{tag} = 'BINARY';

    # Attributes (none)

    # Child elements
    foreach $node ($vo_binary->childNodes) {
	$tag = $node->nodeName;
	if ($tag eq 'STREAM') {
	    push(@{$binary->{elements}}, _convert_stream($node));
	} elsif ($tag eq 'comment') {
	} elsif ($tag eq 'text') {
	} else {
	    die("Invalid tag for BINARY child: $tag!");
	}
    }

    # Text content (none)

    return($binary);
}

#------------------------------------------------------------------------------

sub _convert_stream($)
{
    my($dom_stream) = @_;
    my($vo_stream);
    my($stream);
    my($type, $href, $actuate, $encoding, $expires, $rights);
    my($text);

    $vo_stream = Astro::VO::VOTable::STREAM->new($dom_stream);
    $stream = {};
    $stream->{tag} = 'STREAM';

    # Attributes
    $type = $vo_stream->get_type;
    $href = $vo_stream->get_href;
    $actuate = $vo_stream->get_actuate;
    $encoding = $vo_stream->get_encoding;
    $expires = $vo_stream->get_expires;
    $rights = $vo_stream->get_rights;
    $stream->{attributes}{type} = $type if defined($type);
    $stream->{attributes}{href} = $href if defined($href);
    $stream->{attributes}{actuate} = $actuate if defined($actuate);
    $stream->{attributes}{encoding} = $encoding if defined($encoding);
    $stream->{attributes}{expires} = $expires if defined($expires);
    $stream->{attributes}{rights} = $rights if defined($rights);

    # Child elements (none)

    # Text content (all text)
    $text = $vo_stream->get;
    $stream->{text} = $text;

    return($stream);
}

#------------------------------------------------------------------------------

sub _convert_coosys($)
{
    my($dom_coosys) = @_;
    my($vo_coosys);
    my($coosys);
    my($id, $equinox, $epoch, $system);
    my($node, $tag);
    my($text);

    $vo_coosys = Astro::VO::VOTable::COOSYS->new($dom_coosys);
    $coosys = {};
    $coosys->{tag} = 'COOSYS';

    # Attributes
    $id = $vo_coosys->get_ID;
    $equinox = $vo_coosys->get_equinox;
    $epoch = $vo_coosys->get_epoch;
    $system = $vo_coosys->get_system;
    $coosys->{attributes}{ID} = $id if defined($id);
    $coosys->{attributes}{equinox} = $equinox if defined($equinox);
    $coosys->{attributes}{epoch} = $epoch if defined($epoch);
    $coosys->{attributes}{system} = $system if defined($system);

    # Child elements (none)

    # Text content (ignore whitespace)
    $text = $vo_coosys->get;
    $coosys->{text} = $text if $text =~ /\S/;

    return($coosys);
}
